name: Build GLVD Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: actions/upload-artifact@v4
      with:
        name: glvd-client
        path: glvd-client

  build_arm:
    runs-on: ubuntu-latest
    env:
      GOOARCH: arm64
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: actions/upload-artifact@v4
      with:
        name: glvd-client-arm
        path: glvd-client

  run_in_gl:
    runs-on: ubuntu-latest
    container: ghcr.io/gardenlinux/gardenlinux:1592.1
    needs:
      - build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - run: cat /etc/os-release
    - run: ls -lR
    - run: chmod +x glvd-client/glvd-client
    - run: ./glvd-client/glvd-client
